---
{{- if .Values.ingress.enable -}}
{{- $fullName := include "omnitruck.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "omnitruck.fullname" . }}
  labels:
    {{- include "omnitruck.commonLabels" . | nindent 4 }}
spec:
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingressClassName }}
  defaultBackend:
    service:
      name: {{ include "omnitruck.fullname" . }}
      port:
        number: {{ default "8080" .Values.service.port | int }}
  {{- end }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ default "8080" $svcPort | int }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ default "8080" $svcPort | int }}
              {{- end }}
    {{- end }}
{{- end -}}
