---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omnitruck.serviceAccountName" . }}
  labels:
    {{- include "omnitruck.commonLabels" . | nindent 4 }}
{{- end -}}