---
{{- if .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnitruck.fullname" . }}
  labels:
    {{- include "omnitruck.commonLabels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - port: {{ default "8080" .Values.service.port | int }}
      targetPort: 8080
      protocol: {{ default "TCP" .Values.service.protocol }}
      name: http
  selector:
    {{- include "omnitruck.selectorLabels" . | nindent 4 }}
{{- end -}}
